import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bantuan sosial dana',
  description: 'Generated by M Aqmal H',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
       
        {children}
        

       <Script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' />
      </body>
    </html>
  )
}
